In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\naveen s kamatagi\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\naveen s kamatagi\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\naveen s kamatagi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\naveen s kamatagi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\naveen s kamatagi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\naveen s kamatagi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df=pd.DataFrame([11,25,254,545],columns=["col_nam"])

In [4]:
df=pd.DataFrame([11,25,254,545],columns=["Col_nam"])
print(df)

   Col_nam
0       11
1       25
2      254
3      545

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [6]:
data ={
    'Name': ["naveen", "omkar","vikas","om"],
    'Age': [45,25,55,21],
    'Salary': [25000,23555,56110,45000],
    'ID': [101,201,301,401]
}

In [7]:
df= pd.DataFrame(data)
print(df)

     Name  Age  Salary   ID
0  naveen   45   25000  101
1   omkar   25   23555  201
2   vikas   55   56110  301
3      om   21   45000  401

In [13]:
df

     Name  Age  Salary
0  naveen   45   25000
1   omkar   25   23555
2   vikas   55   56110
3      om   21   45000

In [14]:
df.head(3)

     Name  Age  Salary
0  naveen   45   25000
1   omkar   25   23555
2   vikas   55   56110

In [15]:
df.head(1)

     Name  Age  Salary
0  naveen   45   25000

In [16]:
df.tail(2)

    Name  Age  Salary
2  vikas   55   56110
3     om   21   45000

In [17]:
df.tail(1)

  Name  Age  Salary
3   om   21   45000

In [18]:
df.shape

(4, 3)

In [19]:
df.shape

(4, 3)

In [21]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [23]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [24]:
df

     Name  Age  Salary
0  naveen   45   25000
1   omkar   25   23555
2   vikas   55   56110
3      om   21   45000

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [26]:
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   36.500000  37416.250000
std    16.196707  15845.788807
min    21.000000  23555.000000
25%    24.000000  24638.750000
50%    35.000000  35000.000000
75%    47.500000  47777.500000
max    55.000000  56110.000000

In [8]:
df

     Name  Age  Salary   ID
0  naveen   45   25000  101
1   omkar   25   23555  201
2   vikas   55   56110  301
3      om   21   45000  401